### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [1]:
#Importing tensorflow
import tensorflow as tf

#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
#Importing fashion_mnist sub-module from keras.datasets module in tensorflow library
from tensorflow.keras.datasets import fashion_mnist

#Load Fashion mnist data
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

#### Change train and test labels into one-hot vectors

In [3]:
#Changing train & test labels into one-hot vectors
y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

#Printing top 5 records to verify
print(y_train[:5])
print(y_test[:5])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
#Import Sequential sub-module from keras.models module in tensorflow library
from tensorflow.keras.models import Sequential

#Initialize Model
model = Sequential()

#Reshape 28 x 28 images to flatten it
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

#Normalize inputs from 0-255 to 0-1
x_train = x_train / 255.0
x_test = x_test / 255.0

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [5]:
#Import Dense & Dropout sub-modules from keras.layers module in tensorflow library
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

#Adding fully connected layer with 200 neurons with relu activation
model.add(Dense(200, input_shape=(784,), activation='relu'))

#Adding fully connected layer with 100 neurons with relu activation
model.add(Dense(100, activation='relu'))

#Adding dropout layer with p=0.25
model.add(Dropout(0.25))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [6]:
#Adding output layer with 10 neurons with softmax activation
model.add(Dense(10, activation='softmax'))

#Compile model using categorical_crossentropy loss & adam optimizer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#Train the network with 100 epochs
model.fit(x_train, y_train, epochs=100, verbose=1, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/100
60000/60000 [==============================] - 6s 96us/sample - loss: 0.5134 - acc: 0.8174 - val_loss: 0.4092 - val_acc: 0.8500
Epoch 2/100
60000/60000 [==============================] - 6s 94us/sample - loss: 0.3811 - acc: 0.8621 - val_loss: 0.3921 - val_acc: 0.8525
Epoch 3/100
60000/60000 [==============================] - 6s 101us/sample - loss: 0.3479 - acc: 0.8723 - val_loss: 0.3542 - val_acc: 0.8705
Epoch 4/100
60000/60000 [==============================] - 6s 97us/sample - loss: 0.3247 - acc: 0.8811 - val_loss: 0.3684 - val_acc: 0.8710
Epoch 5/100
60000/60000 [==============================] - 5s 91us/sample - loss: 0.3067 - acc: 0.8862 - val_loss: 0.3423 - val_acc: 0.8806
Epoch 6/100
60000/60000 [==============================] - 6s 95us/sample - loss: 0.2909 - acc: 0.8921 - val_loss: 0.3385 - val_acc: 0.8790
Epoch 7/100
60000/60000 [==============================] - 6s 94us/sample - loss: 0.2803 - acc: 0.8965 - val_

In [0]:
#After 100 Epochs, we can see that validation accuracy is 89.53%.
#But, training accuracy of 96.65% is lot higher than validation accuracy which suggests that this model has overfitted the training data which often is the problem with Deep Neural Networks which is alo evident from the fact that validation loss is almost 10 times the training loss.
#So, to improve this model, we would have to use some regularizing techniques like Dropout layer, Batch normalization or L1 & L2 Regularization techniques.
#Another way is to try increasing the Training dataset size. But, many a times, this isn't very feasible.
#So, we can use Data Augmentation techniques to artificially increase Training dataset size which would avoid model to overfit the training data.