# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [0]:
import pandas as pd
from sklearn.datasets import load_iris

In [0]:
iris_df = load_iris()

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [0]:
X = iris_df.data
y = iris_df.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np

In [0]:
X = np.array(X).astype('float32')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [0]:
y_train = tf.keras.utils.to_categorical(y_train, 3, dtype=np.bool)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [0]:
model = tf.keras.models.Sequential()

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [0]:
model.add(tf.keras.layers.Dense(3, input_dim=4, activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [14]:
model.fit(X_train, y_train, epochs=100)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 4ms/sample - loss: 2.7185 - accuracy: 0.3125
Epoch 2/100
112/112 [==============================] - 0s 149us/sample - loss: 1.6472 - accuracy: 0.3125
Epoch 3/100
112/112 [==============================] - 0s 123us/sample - loss: 1.3243 - accuracy: 0.1339
Epoch 4/100
112/112 [==============================] - 0s 129us/sample - loss: 1.2200 - accuracy: 0.2679
Epoch 5/100
112/112 [==============================] - 0s 113us/sample - loss: 1.1777 - accuracy: 0.2857
Epoch 6/100
112/112 [==============================] - 0s 115us/sample - loss: 1.1372 - accuracy: 0.2411
Epoch 7/100
112/112 [==============================] - 0s 105us/sample - loss: 1.1061 - accuracy: 0.2500
Epoch 8/100
112/112 [==============================] - 0s 129us/sample - loss: 1.0769 - accuracy: 0.2768
Epoch 9/100
112/112 [==============================] - 0s 123us/sample - loss: 1.0607 - accuracy: 0.2411
Epoch 10/100
112/112 [==============

## Question 10

### Make predictions
- Predict labels on one row

In [15]:
y_pred=model.predict(X_test)
print(y_pred)

[[0.06274511 0.58554804 0.35170686]
 [0.87817246 0.08279598 0.03903156]
 [0.00306759 0.5244887  0.47244367]
 [0.05939376 0.4607407  0.47986558]
 [0.05696499 0.6127164  0.33031863]
 [0.8435308  0.10373404 0.05273528]
 [0.14886339 0.4175473  0.4335893 ]
 [0.01994389 0.31332925 0.6667269 ]
 [0.03768009 0.5974092  0.36491072]
 [0.11546741 0.51960397 0.36492857]
 [0.02665482 0.34210947 0.6312357 ]
 [0.82616276 0.1272968  0.04654052]
 [0.8979124  0.073383   0.02870464]
 [0.8268019  0.12685211 0.04634605]
 [0.8833502  0.07013658 0.04651317]
 [0.06351539 0.410829   0.52565557]
 [0.00890047 0.3231171  0.6679824 ]
 [0.10376109 0.5591062  0.33713272]
 [0.0620003  0.50111634 0.43688342]
 [0.00920571 0.33472756 0.6560667 ]
 [0.8043538  0.13085471 0.06479157]
 [0.03139925 0.37897578 0.58962494]
 [0.81358397 0.11447278 0.07194319]
 [0.01049991 0.3660926  0.62340754]
 [0.01841823 0.4602377  0.521344  ]
 [0.0155447  0.3057858  0.6786695 ]
 [0.01090955 0.5557217  0.4333688 ]
 [0.00906034 0.30353057 0.68

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [16]:
out = []
for val in y_pred:
    out.append(np.argmax(val))
print(out)

[1, 0, 1, 2, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2, 0, 2, 2, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0]


In [0]:
from sklearn.metrics import confusion_matrix

In [18]:
confusion_matrix(y_test, out)

array([[15,  0,  0],
       [ 0,  7,  4],
       [ 0,  2, 10]])

In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, out)

0.8421052631578947



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [0]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [21]:
import tensorflow as tf
print(tf.__version__)

2.1.0-rc1


### Set random seed

In [0]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [0]:
# run this cell to upload file if you are using google colab
from google.colab import files
#files.upload()

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
prices_df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/prices.csv')

In [26]:
prices_df.head()

date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [27]:
prices_df.drop(['date','symbol'], axis=1, inplace=True)
prices_df.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [28]:
prices_df = prices_df.iloc[:1000,:]
prices_df.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [0]:
X = prices_df.iloc[:,:-1]
y = prices_df.iloc[:,-1]
y /= 1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [0]:
X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.float32)

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [0]:
X_normal = tf.math.l2_normalize(X,1)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [0]:
W = tf.Variable( tf.zeros( [4,1] ) )
B = tf.Variable( tf.zeros( [1] ) )

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [0]:
def prediction(x, w, b):
  return tf.matmul( x, w ) + b

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [0]:
def loss(predicted_y, desired_y):
  return tf.reduce_mean(tf.square(predicted_y - desired_y))

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
def train(X1, y1, epochs):
  optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)
  
  for i in range(epochs):
    with tf.GradientTape() as tape: #tf.GradientTape records all operations in forward pass to apply gradient later
      predicted = prediction( X1,W,B )
      curr_loss = loss(predicted, y)
    grads = tape.gradient( curr_loss, [W,B] )#return derivative of loss function wrt weight and bias
    optimizer.apply_gradients(zip(grads, [W,B])) #applys Gradient Descent
    print("Loss at step {:d}: {:.3f}".format(i, loss(prediction( X1,W,B ), y1)))

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [36]:
train(X_normal,y,100)

Loss at step 0: 235.073
Loss at step 1: 233.032
Loss at step 2: 231.152
Loss at step 3: 229.419
Loss at step 4: 227.821
Loss at step 5: 226.349
Loss at step 6: 224.993
Loss at step 7: 223.743
Loss at step 8: 222.590
Loss at step 9: 221.529
Loss at step 10: 220.550
Loss at step 11: 219.648
Loss at step 12: 218.817
Loss at step 13: 218.051
Loss at step 14: 217.345
Loss at step 15: 216.694
Loss at step 16: 216.095
Loss at step 17: 215.542
Loss at step 18: 215.033
Loss at step 19: 214.563
Loss at step 20: 214.131
Loss at step 21: 213.732
Loss at step 22: 213.365
Loss at step 23: 213.026
Loss at step 24: 212.714
Loss at step 25: 212.426
Loss at step 26: 212.161
Loss at step 27: 211.917
Loss at step 28: 211.692
Loss at step 29: 211.485
Loss at step 30: 211.293
Loss at step 31: 211.117
Loss at step 32: 210.955
Loss at step 33: 210.805
Loss at step 34: 210.667
Loss at step 35: 210.540
Loss at step 36: 210.423
Loss at step 37: 210.315
Loss at step 38: 210.215
Loss at step 39: 210.124
Loss at st

### Observe values of Weight
- Print the updated values

In [37]:
print(W)

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[1.304366 ],
       [1.3088913],
       [1.2909067],
       [1.3202268]], dtype=float32)>


### Observe values of Bias
- Print the updated values

In [38]:
print(B)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.612345], dtype=float32)>
